server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://postgres.cve67twiaqf9.ap-southeast-1.rds.amazonaws.com:5432/uaa?useSSL=false
    username: postgres
    password: mydb123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



